export default {
  // __typename        :'ExpressionNode',
  content           :'Loading',
  correctedContent  :'Loading',
  iso6391           :'**',
  iso6392           :'***',
  iso6393           :'***',
  grammarExplanation:'Loading',
  generalExplanation:'Loading',
  wordsExplanation  :'Loading',
  rating            :null,
  ratingComment     :null,
  isBookmarked      :false,
  audioUrl          :'',
  changes           :'Loading',
  isProcessed       :false,
  isNew             :true,
  translation       :null,
}
